### ISSUE TITLE
Is Chat-bison model good for batch evaluation? 

### ISSUE THREAD

**Issue by findalexli** [GoogleCloudPlatform/generative-ai#102]
I only saw the tutorial on  batch evaluation for base text-bison model, but not the chat-bison model. But the feature page does mention chat-bison has Batch requests capability. Is it turned on now?

**Comment by polong-lin** [comment]
Hi @findalexli , I'm not entirely sure I understand -- could you kindly elaborate on what you are hoping to achieve with doing batch requests to a chat model? I just want to make sure I'm understanding the question correctly before trying to answer. Thank you!

**Comment by holtskinner** [comment]
The documentation has been updated to say: 

https://cloud.google.com/vertex-ai/docs/generative-ai/model-reference/text-chat

> For text tasks that can be completed with one API response (without the need for continuous conversation), use the [Text model](https://cloud.google.com/vertex-ai/docs/generative-ai/model-reference/text).
