### ISSUE TITLE
[Feat]: Add Logprobs for Each Token

### ISSUE THREAD

**Issue by JP-Leite** [GoogleCloudPlatform/generative-ai#1063]
### Describe the solution you'd like

Please add functionality to return log probabilities (logprobs) for each token in the generated output. This will help measure the model’s confidence in its predictions at a granular level, providing valuable insights into decision-making during token generation. OpenAI's models already support logprobs and top logprobs, so extending this feature to return logprobs for each token would align.

Benefit:
This feature will allow users to track model confidence per token, facilitating more informed adjustments to responses, debugging, and output evaluation.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gericdong** [comment]
Thanks for the feedback! 
responseLogprobs and logprobs are being supported in Gemini API as public preview. https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/inference
