### ISSUE TITLE
[Bug]: Getting started with Vertex AI Gemini 1.5 Pro: PDF document analysis observation

### ISSUE THREAD

**Issue by G1tPlunge** [GoogleCloudPlatform/generative-ai#1164]
### File Name

intro_gemini_1_5_pro.ipynb

### What happened?

In PDF document analysis:

- 3rd code block doesn't work as is. I got a message to indicate the file and image needed for that section.
- After I modified the content section from pdf_file to pdf_file_uri and then re-ran the block, I got the intended output.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gericdong** [comment]
Thanks for reporting the issue. The notebook has been updated.
