### ISSUE TITLE
[Bug]: Getting started with Vertex AI Gemini 1.5 Pro: Audio Understanding observation 2

### ISSUE THREAD

**Issue by G1tPlunge** [GoogleCloudPlatform/generative-ai#1166]
### File Name

intro_gemini_1_5_pro.ipynb

### What happened?

In the Audio Understanding section of the notebook:

- As far as I can tell, the mp3 has 4 distinct voices: the host, the voice that announces the name of the podcast and host, and the two guests. Transcription lists 5 speakers (A, B, C, D and E).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gericdong** [comment]
Thanks for reporting this issue. While we're improving the model quality, there are still some limitations with the audio understanding with Gemini (https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/audio-understanding#limitations)
