### ISSUE TITLE
Ensemble LLMs to get better results: Suggestion for new example

### ISSUE THREAD

**Issue by yogeshhk** [GoogleCloudPlatform/generative-ai#120]
Each LLM model has its own strength, has its own diverse corpus. Rather than relying on one LLM at a time, to get response, why not employ multiple LLMs and then get the best result by ranking the responses?

Steps for any problem:
- Have multiple LLMs in ensemble (for-loop)
- Let each LLM respond to the given prompt, collect responses from each
- Let each LLM rank the responses from all the LLMs.
- Aggregate the ranks, or some way of majority, find the best response.

**Comment by gericdong** [comment]
Thank you for the suggestion! We have taken this feedback into consideration for best practices.
