### ISSUE TITLE
Add Documentation on Policies and Permissions Needed

### ISSUE THREAD

**Issue by j-f-oleary-bigdata** [GoogleCloudPlatform/generative-ai#123]
In order to get this demo to work I had to make two changes:

1.) set constraints/iam.allowedPolicyMemberDomains to allow all
2.) Give cloudrun service account (by default the default compute service account) discoveryengine.viewer permissions

**Comment by iamthuya** [comment]
Hi. Can you specify which demo? It will be great if you can provide a specific notebook that you are referring to. Thanks!

**Comment by j-f-oleary-bigdata** [comment]
The error was found when running the search-web-app.
