### ISSUE TITLE
steps to creating datastore missing in data_store_checker notebook

### ISSUE THREAD

**Issue by sathishvj** [GoogleCloudPlatform/generative-ai#143]
[data_store_checker.ipynb](https://github.com/GoogleCloudPlatform/generative-ai/blob/main/gen-app-builder/data-store-status-checker/data_store_checker.ipynb) does not show the steps to create the data store. This might make the notebook difficult to learn from for those new to the topic.

Solution: we should add the steps to creating the datastore.

**Comment by holtskinner** [comment]
This wasn't added to the Data Store Checker notebook because creation wasn't supported through the API at the time.

The creation steps have now been added to https://github.com/GoogleCloudPlatform/generative-ai/blob/main/search/create_datastore_and_search.ipynb
