### ISSUE TITLE
[Bug]: RAG Engine readme has an incorrect link

### ISSUE THREAD

**Issue by kazunori279** [GoogleCloudPlatform/generative-ai#1455]
### File Name

https://github.com/GoogleCloudPlatform/generative-ai/blob/main/rag-grounding/README.md

### What happened?

This line should have a link to the RAG Engine + VVS notebook. (btw great work on the notebook! shared with the VVS PM).

https://github.com/GoogleCloudPlatform/generative-ai/blob/86f4e0b263631bf5452178c553b8e9bea8af1f3d/rag-grounding/README.md?plain=1#L101

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by holtskinner** [comment]
Fixed in https://github.com/GoogleCloudPlatform/generative-ai/commit/ddce39ac071f3a24eb322e69c5d4d092d5880f7c

**Comment by kazunori279** [comment]
Thanks!!
