### ISSUE TITLE
[Bug]: Logprobs not supported for gemini-1.5-flash-8b

### ISSUE THREAD

**Issue by Kedaqusa1604** [GoogleCloudPlatform/generative-ai#1536]
### File Name

.

### What happened?

Hi there, I'm trying to obtain the response_logprobs of a generated response by gemini-1.5-flash-8b, however I'm getting this error:

```py
google.api_core.exceptions.InvalidArgument: 400 Logprobs is not supported for the current model
```

Will this feature be available soon? Or it won't be implemented?

### Relevant log output

```shell
google.api_core.exceptions.InvalidArgument: 400 Logprobs is not supported for the current model
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gericdong** [comment]
@Kedaqusa1604 : `response_logprobs` has been implemented but it hasn't been made generally available. Please check the status here: https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/content-generation-parameters#advanced-parameters. Thanks.
