### ISSUE TITLE
[Bug]: imagen-3.0-capability-001 is unavailable

### ISSUE THREAD

**Issue by benpowis** [GoogleCloudPlatform/generative-ai#1546]
### File Name

generative-ai/blob/main/vision/getting-started/imagen3_editing.ipynb

### What happened?

Hi there, I understand from reading the Imagen3 example notebook (https://github.com/GoogleCloudPlatform/generative-ai/blob/main/vision/getting-started/imagen3_editing.ipynb) that one must instanciate an image editing model using like so:
`edit_model = ImageGenerationModel.from_pretrained("imagen-3.0-capability-001")`

When I do this in my code I get the error message:
`NotFound: 404 Image editing failed with the following error: imagen-3.0-capability-001 is unavailable.`

I am using version 1.74.0 of google-cloud-aiplatform.

How can I get access to the capability model?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by katiemn** [comment]
Hi @benpowis, Imagen 3 editing is generally available but requires approval, https://cloud.google.com/vertex-ai/generative-ai/docs/image/overview#feature-launch-stage. To request access you can fill out this [form](https://docs.google.com/forms/d/e/1FAIpQLScN9KOtbuwnEh6pV7xjxib5up5kG_uPqnBtJ8GcubZ6M3i5Cw/viewform).

**Comment by karm435** [comment]
How long does it take for this to get approved?

**Comment by adriamesas** [comment]
> How long does it take for this to get approved?

:)

**Comment by adriamesas** [comment]
Do we know anything yet about timings?
