### ISSUE TITLE
'from utils.matching_engine' fails

### ISSUE THREAD

**Issue by stevewalker-de** [GoogleCloudPlatform/generative-ai#156]
Need to ghclone:
!ghclone https://github.com/GoogleCloudPlatform/generative-ai/tree/main/language/examples/document-qa/utils

Then this works
# Import custom Matching Engine packages
from utils.matching_engine import MatchingEngine
from utils.matching_engine_utils import MatchingEngineUtils

**Comment by polong-lin** [comment]
Thanks Steve! Should be fixed now in https://github.com/GoogleCloudPlatform/generative-ai/pull/164
