### ISSUE TITLE
Json file based QA model

### ISSUE THREAD

**Issue by karthi7CK** [GoogleCloudPlatform/generative-ai#172]
I'm trying to replicate the document based question and answering model but instead of the reading and storing the document in the chromoDB. I want to read the Json file and store it in the chromoDB. If user requested any questions then it should reply from the json file. So, the json file is the source for QA model. The size of json file is huge so I need to do chunking also.

**Comment by holtskinner** [comment]
I think this is the notebook referenced here: https://github.com/GoogleCloudPlatform/generative-ai/blob/main/language/use-cases/document-qa/question_answering_documents_langchain.ipynb

@inardini Can you take a look?
