### ISSUE TITLE
Custom TF Model with Generative AI (PaLM API)

### ISSUE THREAD

**Issue by SNNJM** [GoogleCloudPlatform/generative-ai#178]
Hi,

I'm wondering if I could actually use my custom Tensorflow ML model with PaLM API (Gen AI), for example I saved tf model in .h5 format and import it in PaLM AI and expect questions that were asked are answered according to the custom model I trained.

I've been reading the official documentation, however, most are explaining the use of text models, etc instead of a custom model.

**Comment by holtskinner** [comment]
You are able to deploy a custom Tensorflow model to Google Cloud Vertex AI by using the documentation listed here:

- https://cloud.google.com/vertex-ai/docs/start/tensorflow

Here's a video series from Google Cloud that shows how to use Vertex AI:

- [Google Cloud Tech - Prototype to Production](https://www.youtube.com/watch?v=_Q1Nf-rgSiE&list=PLIivdWyY5sqJAyUJbbsc8ZyGLNT4isnuB&index=1)

Here's a blog post that also explains the process

- https://towardsdatascience.com/how-to-deploy-a-tensorflow-model-to-vertex-ai-87d9ae1df56
