### ISSUE TITLE
gunicorn failure on cloud run example

### ISSUE THREAD

**Issue by guilhem-martin** [GoogleCloudPlatform/generative-ai#198]
Hello,

I'm running the search webapp following the [readme](https://github.com/GoogleCloudPlatform/generative-ai/tree/main/search/web-app). The cloud run is successfully built but raises errors when deployed:

`Traceback (most recent call last): File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker worker.init_process() File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/gthread.py", line 95, in init_process super().init_process() File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process self.load_wsgi() File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi self.wsgi = self.app.wsgi()`

The cloud run web page displays "service not available".

I tried several verion of gunicorn through the Dockerfile, but it didn't help.

Any idea?
Thanks.

**Comment by ChunKinPS** [comment]
Same here, finding solution as well

**Comment by guilhem-martin** [comment]
@ChunKinPS 
What I just tried: gunicorn==21.2.0 in the requirements.txt and still 3.11 for python in the Dockerfile.
But still getting the same error.

**Comment by ChunKinPS** [comment]
@guilhem-martin I had solved the issue. Simply remove the version for all the dependencies in requirements.txt . For my case, it solved the issue.

**Comment by adityaworkfusion** [comment]
I am also getting same issue with gunicorn. Basically I have deployed a python gen app on google cloud run with gunicorn version "20.1.0" but its giving me same error above user are facing.

Though with the same gunicorn version I was able to run it earlier on cloud run, please suggest me how I can fix this issue.

**Comment by ChunKinPS** [comment]
> I am also getting same issue with gunicorn. Basically I have deployed a python gen app on google cloud run with gunicorn version "20.1.0" but its giving me same error as above user are facing. Though with the same gunicorn version I was able to run it earlier on cloud run, please suggest me how I can fix this issue.
> 
> below is the error
> 
> Traceback (most recent call last): File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker worker.init_process() File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/gthread.py", line 95, in init_process super().init_process() File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process self.load_wsgi() File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi self.wsgi = self.app.wsgi()

Did u try remove the version in requirements.txt? after I remove the version, I deploy again and the issue solved. I think this is because the version of python and gunicorn causing this issue. There is some conflict over there. I am using python:3.11-slim in my dockerfile as well like you.
![image](https://github.com/GoogleCloudPlatform/generative-ai/assets/142908742/cd96c834-f84f-429a-8780-3944b58124e1)

**Comment by adityaworkfusion** [comment]
Thanks,  I will try without passing any version, but what's the fix when I have version dependencies for few libraries.

**Comment by ChunKinPS** [comment]
One possible solution is keep trying for different version until you did not see the error.

**Comment by hugomiura** [comment]
I got the same error. I also removed all versions from requirements but it nothing changed.

`Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/gthread.py", line 95, in init_process
    super().init_process()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi() `

**Comment by holtskinner** [comment]
https://github.com/GoogleCloudPlatform/generative-ai/blob/main/search/web-app/requirements.txt doesn't have a version for `gunicorn` or any other library except `google-cloud-discoveryengine>=0.11.1`.

Have you also set the `PROJECT_ID` and other config variables to your own values?

And setup a Vertex AI Search app in the project?
