### ISSUE TITLE
Vector Search notebook not functional 

### ISSUE THREAD

**Issue by valkyriekngt** [GoogleCloudPlatform/generative-ai#200]
DocAI OCR only reads the first few pages of the doc and the rest of the entire document is empty

![image](https://github.com/GoogleCloudPlatform/generative-ai/assets/35805809/5e873ae5-671b-43a5-8dcb-a0b858571f16)

In addition, after going through the chunking process, pdf_data_sample.chunks is completely empty. No content is stored. 

![image](https://github.com/GoogleCloudPlatform/generative-ai/assets/35805809/e83f9790-79f5-4f4f-95d1-e42bf1e726b8)

**Comment by holtskinner** [comment]
I believe this is the same issue as #217 

Fixed in #232
