### ISSUE TITLE
Input Tokens Count in ChatBison

### ISSUE THREAD

**Issue by N1RM4L13** [GoogleCloudPlatform/generative-ai#204]
Im using ChatBison to get answers from a piece of text , suppose I give input text using palm.chat() and then ask questions using palm.reply(). Does the conversation also include previous historical text as input again and again ?

**Comment by holtskinner** [comment]
Yes, `chat-bison` preserves chat history and context for future calls.

Here is a more detailed description: https://g.co/bard/share/4207b5ca066b

Note - This repository is focused on Generative AI with Google Cloud Vertex AI, not the [Google AI for Developers Gemini API or PaLM API](https://ai.google.dev/docs).
