### ISSUE TITLE
Getting `TypeError` when using LangChain 0.0.316 in `search/retrieval-augmented-generation/examples/question_answering.ipynb`

### ISSUE THREAD

**Issue by matthiasa4** [GoogleCloudPlatform/generative-ai#231]
When trying the example in `search/retrieval-augmented-generation/examples/question_answering.ipynb` I am getting: `TypeError: TextGenerationModel.predict() got an unexpected keyword argument 'candidate_count'`.

After changing to version `0.0.310` as per [this issue](https://github.com/GoogleCloudPlatform/generative-ai/blob/main/search/retrieval-augmented-generation/examples/question_answering.ipynb) the notebook seems to run as expected. But it misses `GoogleVertexAIMultiTurnSearchRetriever`.

**Comment by holtskinner** [comment]
I was able to reproduce this when using `google-cloud-aiplatform==1.34.0` with `langchain==0.0.316`

However, it doesn't occur when using `google-cloud-aiplatform==1.35.0`

PR #232 should fix this

**Comment by matthiasa4** [comment]
Thanks @holtskinner !
