### ISSUE TITLE
Random Seed

### ISSUE THREAD

**Issue by pharringtonp19** [GoogleCloudPlatform/generative-ai#289]
OpenAI has a way to set the [seed](https://cookbook.openai.com/examples/deterministic_outputs_with_the_seed_parameter). Is there a way to do this with gemini models?

**Comment by holtskinner** [comment]
@pharringtonp19 You can set the seed in the Vertex AI API as illustrated [here for PaLM Text Generation][1]

And [here for Image Captioning][2]

It doesn't look like Gemini currently supports providing a seed.

- https://cloud.google.com/vertex-ai/docs/generative-ai/model-reference/gemini

- https://cloud.google.com/vertex-ai/docs/reference/rest/v1/projects.locations.publishers.models/streamGenerateContent

[1]: https://cloud.google.com/vertex-ai/docs/generative-ai/model-reference/text#generative-ai-text-prompt-python_vertex_ai_sdk:~:text=Optional-,seed,-Decoder%20generates%20random
[2]: https://cloud.google.com/vertex-ai/docs/generative-ai/image/image-captioning#seed

**Comment by andrewssobral** [comment]
any news on that?

**Comment by boxabirds** [comment]
Yeah Google Gemini isn't a viable software engineering API if you can't fix the seed to get deterministic output.

**Comment by taurit** [comment]
I think it's possible now. Tested with `gemini-1.5-flash` and older `gemini-1.0-pro`. Both seem to respond deterministically with this parameter set:

```jsonc
// POST https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent

{
  "contents": [ { "parts": [ { "text": "What are the capitals of France, Spain, Poland?" } ] } ],
  "generationConfig": {
    "seed": 123456
  }
}
```

[API Reference](https://cloud.google.com/vertex-ai/docs/generative-ai/model-reference/gemini) here.

**Comment by binaryblood** [comment]
this is still not compatible with openai library.

`from openai import OpenAI
client = OpenAI(base_url="https://generativelanguage.googleapis.com/v1beta/openai/", 
                api_key=os.environ.get("GEMINI_API_KEY"))

response = client.chat.completions.create(
  model="gemini-1.5-flash",
  messages=[
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": "Hello!"}
  ],
  stream=False,
  max_tokens=1000,
  seed=1234,
  temperature=0.5
)

print(response.choices[0].message.content)`

give error
`BadRequestError: Error code: 400 - [{'error': {'code': 400, 'message': 'Invalid JSON payload received. Unknown name "seed": Cannot find field.'`

If Google doesn't support switching to gemini with quick changes, it will lack adoption.

**Comment by gonzaferreiro** [comment]
> https://generativelanguage.googleapis.com/v1beta/openai/

We would greatly appreciate support with this too - we want to fully migrate to Gemini, but we need to be able to set a random seed for the sake of unit testing.

**Comment by gonzaferreiro** [comment]
> this is still not compatible with openai library.
> 
> `from openai import OpenAI client = OpenAI(base_url="https://generativelanguage.googleapis.com/v1beta/openai/", api_key=os.environ.get("GEMINI_API_KEY"))
> 
> response = client.chat.completions.create( model="gemini-1.5-flash", messages=[ {"role": "system", "content": "You are a helpful assistant."}, {"role": "user", "content": "Hello!"} ], stream=False, max_tokens=1000, seed=1234, temperature=0.5 )
> 
> print(response.choices[0].message.content)`
> 
> give error `BadRequestError: Error code: 400 - [{'error': {'code': 400, 'message': 'Invalid JSON payload received. Unknown name "seed": Cannot find field.'`
> 
> If Google doesn't support switching to gemini with quick changes, it will lack adoption.

We would greatly appreciate support with this too @holtskinner - we want to fully migrate to Gemini, but we need to be able to set a random seed for the sake of unit testing.

**Comment by boxabirds** [comment]
So apparently the latest is that setting temperature to 0 will result in
deterministic output but I haven’t tested it though.

https://ai.google.dev/gemini-api/docs/prompting-strategies

If it’s any use, AWS bedrock makes the same promise but fails on it’s nova
pro models so I’m guessing that determinism is probably model specific.
