### ISSUE TITLE
base nodejs，Need to be able to pass in the agent, thx

### ISSUE THREAD

**Issue by lbjfish** [GoogleCloudPlatform/generative-ai#301]
base nodejs，Need to be able to pass in the agent, thx
The current interface uses fetch, and I hope to provide agent proxy parameters.

```js
async function makeRequest(url, body) {
    let response;
    try {
        response = await fetch(url, {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "x-goog-api-client": getClientHeaders(),
            },
            body,
        });
        if (!response.ok) {
            let message = "";
            try {
                const json = await response.json();
                message = json.error.message;
                if (json.error.details) {
                    message += ` ${JSON.stringify(json.error.details)}`;
                }
            }
            catch (e) {
                // ignored
            }
            throw new Error(`[${response.status} ${response.statusText}] ${message}`);
        }
    }
    catch (e) {
        const err = new GoogleGenerativeAIError(`Error fetching from ${url}: ${e.message}`);
        err.stack = e.stack;
        throw err;
    }
    return response;
}
```

**Comment by holtskinner** [comment]
Can you provide more context on this issue?

Which Notebook is this occurring in?

**Comment by holtskinner** [comment]
This repository is for [Generative AI with Vertex AI on Google Cloud](https://cloud.google.com/vertex-ai/docs/generative-ai/learn/overview), not the [Google AI Gemini/PaLM APIs](https://ai.google.dev/).

This looks like it could be the JavaScript client library, so you can try filing an issue in this repository:

https://github.com/google/generative-ai-js

or ask in the [Google Developers Community Discord #gemini-api channel](https://ai.google.dev/docs/discord).
