### ISSUE TITLE
Google CLA failure on all Pull Requests

### ISSUE THREAD

**Issue by holtskinner** [GoogleCloudPlatform/generative-ai#303]
Issue source:
https://github.com/GoogleCloudPlatform/generative-ai/commit/c2b2a75031646167fb04cec187504e41dec4e710

Commit message includes:

```
---------

Co-authored-by: Megha Agarwal 
Co-authored-by: Polong Lin <polong-lin@users.noreply.github.com>
```

Co-author Megha Agarwal doesn't have an email added (should be `<meghaag@google.com>` )

However, updating this commit message is a breaking change that requires significant effort to rebase all commits after this.

**Comment by holtskinner** [comment]
@meredithslota We had discussed this last year, is there anything that could be done to change the specific commit message, but not require a full rebasing?

**Comment by meredithslota** [comment]
Followed up on internal bug.
