### ISSUE TITLE
Are there ways to improve the accuracy of Question Answering?

### ISSUE THREAD

**Issue by gvzdv** [GoogleCloudPlatform/generative-ai#331]
I followed the instructions from [this notebook](https://github.com/GoogleCloudPlatform/generative-ai/blob/main/language/use-cases/document-qa/question_answering_documents_langchain_matching_engine.ipynb) and started with just one document, [a driving guide for British Columbia](https://www.icbc.com/driver-licensing/driving-guides/Learn-to-Drive-Smart).

While the model manages to answer some questions, a lot of answers even to simple questions (like "what does flashing green light mean?" or "can you cross a solid yellow line?") are either wrong or said to be unavailable (despite the document containing them).

Is there a way to improve the accuracy of matching?

**Comment by admatt01** [comment]
I think you might've run into the number of pages limitation.

<html>
<body>
<h2 id="Document-AI" style="box-sizing: unset; line-height: var(--jp-content-heading-line-height); font-weight: var(--jp-content-heading-font-weight); font-style: normal; margin-top: calc(0.5 * var(--jp-content-heading-margin-top)); margin-right: ; margin-bottom: ; margin-left: ; font-size: var(--jp-content-font-size4); color: rgba(0, 0, 0, 0.87); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Document AI</h2><p style="box-sizing: unset; margin: 0px 0px 1em; text-align: left; color: rgba(0, 0, 0, 0.87); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">The following<span> </span><a href="https://cloud.google.com/document-ai/quotas" style="box-sizing: unset; color: var(--jp-content-link-color); text-decoration: none;">limits</a><span> </span>apply for online processing with the Document OCR processor.</p>
Limit | Value
-- | --
Maximum file size | 20 MB
**Maximum pages | 15**

<p style="box-sizing: unset; margin: 0px 0px 0.5em; text-align: left; color: rgba(0, 0, 0, 0.87); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">For documents that don't meet these limits, you can use<span> </span><a href="https://cloud.google.com/document-ai/docs/send-request#batch-process" style="box-sizing: unset; color: var(--jp-content-link-color); text-decoration: none;">batch processing</a><span> </span>to extract the document text. (Not covered in this notebook.)</p>
</body>
</html>Document AI
The following [limits](https://cloud.google.com/document-ai/quotas) apply for online processing with the Document OCR processor.

Limit	Value
Maximum file size	20 MB
**Maximum pages	15**
For documents that don't meet these limits, you can use [batch processing](https://cloud.google.com/document-ai/docs/send-request#batch-process) to extract the document text. (Not covered in this notebook.)

**Comment by gericdong** [comment]
Please see comment above. Closing this issue.
