### ISSUE TITLE
'bytes' object has no attribute 'save'

### ISSUE THREAD

**Issue by nwipfli** [GoogleCloudPlatform/generative-ai#339]
When running the notebook [Multimodal Retrieval Augmented Generation (RAG) using Vertex AI Gemini API](https://github.com/GoogleCloudPlatform/generative-ai/blob/main/gemini/use-cases/retrieval-augmented-generation/intro_multimodal_rag.ipynb) I'm getting the following error for the utils intro_multimodal_rag_utils.py when the function "get_document_metadata" is executed.

[/content/utils/intro_multimodal_rag_utils.py](https://localhost:8080/#) in get_document_metadata(project_id, generative_multimodal_model, pdf_path, image_save_dir, image_description_prompt, embedding_size, text_emb_text_limit)
    562             image_metadata[page_num][image_number] = {}
    563 
--> 564             image_for_gemini, image_name = get_image_for_gemini(
    565                 doc, image, image_no, image_save_dir, file_name, page_num
    566             )

[/content/utils/intro_multimodal_rag_utils.py](https://localhost:8080/#) in get_image_for_gemini(doc, image, image_no, image_save_dir, file_name, page_num)
    382 
    383     # Save the image to the specified location
--> 384     data.save(image_name)
    385 
    386     # Load the saved image as a Gemini Image Object

AttributeError: 'bytes' object has no attribute 'save'

**Comment by isidor131908** [comment]
I have the same problem..

**Comment by yosephfernando** [comment]
Same here! Was working perfectly yesterday though.

**Comment by lavinigam-gcp** [comment]
I have raised the PR to fix this bug: https://github.com/GoogleCloudPlatform/generative-ai/pull/343

**Comment by nwipfli** [comment]
I have just tested and it works. Excellent, thanks a lot.
