### ISSUE TITLE
There is problem with Pymupdf in intro_multimodal_rag_utils.py

### ISSUE THREAD

**Issue by ZeeshanHussainKh** [GoogleCloudPlatform/generative-ai#346]
The fitz library is not working or supporting the Pymupdf anyomore.

Kindly resolve.

![error](https://github.com/GoogleCloudPlatform/generative-ai/assets/86972606/608aef82-883d-48d9-8662-8a26ec7a0c53)

**Comment by holtskinner** [comment]
Did PR #343 fix the issue for you?

**Comment by ZeeshanHussainKh** [comment]
Hi yes.

However , I had to downgrade the version of pymupdf  to 1.23.12 and it resolved this issue for me. 

The problem is still present however with the the latest version of pymupdf (1.23.15). It gives an error in the following line of the intro_multimodal_rag_utils.py 

3. import fitz

**Comment by ab-kotecha** [comment]
I was able to solve it with 

!pip install PyMuPDF

instead of 

!pip install pymupdf
