### ISSUE TITLE
`intro_multimodal_rag_utils` has no error handling for safety blocks

### ISSUE THREAD

**Issue by TMRolle** [GoogleCloudPlatform/generative-ai#351]
Relevant file: [`gemini/use-cases/retrieval-augmented-generation/utils/intro_multimodal_rag_utils.py`](https://github.com/GoogleCloudPlatform/generative-ai/blob/main/gemini/use-cases/retrieval-augmented-generation/utils/intro_multimodal_rag_utils.py)

When a document is processed using `get_document_metadata()`, if any of the content in that document is blocked by the Gemini model due to safety filters, it will return a content object without a `.text` property, and will raise a `ValueError("Content has no parts")` if you attempt to reference that field.

It looks like this is not currently handled, resulting in `get_document_metadata()` failing for the whole doc if any of the content trips a safety filter. This was discovered when the safety filters were tripped by a court document referencing criminal activity (which I assume would be considered a false positive).

I'm not very familiar with that module or what use cases it's expected to cover, but I assume it's probably ideal in these cases to catch that exception and output a warning indicating that portions of the document failed to process, while continuing to process the remaining portions of the doc.

**Comment by holtskinner** [comment]
@TMRolle thanks for the catch!

Looks like this is the cause of the issue in #344 .

@lavinigam-gcp Can you take a look and try to find a workaround for this behavior?

**Comment by lavinigam-gcp** [comment]
Working on the fix as of now for this. Will add the PR that fixes this.
