### ISSUE TITLE
generateContentStream  ERROR: TypeError: response.body.pipeThrough is not a function

### ISSUE THREAD

**Issue by stackifyit** [GoogleCloudPlatform/generative-ai#353]
This works:
```
const genAI = new GoogleGenerativeAI(apiKey);
const genModel = genAI.getGenerativeModel({ 'gemini-pro' });
const result = await genModel.generateContent(content);
```

But when I stream, I get the error TypeError: response.body.pipeThrough is not a function:
```
const genAI = new GoogleGenerativeAI(apiKey);
const genModel = genAI.getGenerativeModel({ 'gemini-pro' });
//error occurs here
const result = await genModel.generateContentStream(content);
```

I am using node v21.3.0
npm version @google/generative-ai : "^0.1.3"

**Comment by shanlan-L** [comment]
I also have this problem

**Comment by stackifyit** [comment]
This issue was also created here [google/generative-ai-js/issues/43](https://github.com/google/generative-ai-js/issues/43)

This repo is the one used in the npm package but the other repo appears to actually contain the code effected. Either this issue or the one created in the `generative-ai-js` can be closed once one or the other is addressed.

**Comment by hoantran-it** [comment]
do we have work around in the mean time, I used VertexAI, it was broken today, so I change to new sdk https://ai.google.dev/tutorials/node_quickstart and see this issue

**Comment by holtskinner** [comment]
Hello, thank you for reporting this issue. However, this is not the appropriate repository for the `@google/generative-ai` library.

This repository is primarily focused on Generative AI for Google Cloud, not for Google AI. This issue https://github.com/google/generative-ai-js/issues/43 was created in the correct repository, please follow up there.
