### ISSUE TITLE
[Typescript] type error of history Parts

### ISSUE THREAD

**Issue by liebespaar93** [GoogleCloudPlatform/generative-ai#374]
Hello,

First of all, thank you for creating this library. I am having some TypeScript issues.

Please could you assist me in resolving the following problem?

https://github.com/liebespaar93/map_project_ai/commit/6eb72dc59cdc144033d32c08edb42fe51125f125#diff-afb3871a4296d2ff99af2a936c40f6ff0923a6e39fd161a857bf105e46cb7f5dR76

here is code of some issue
when i use typeof ```InputContent``` it can't find 'text' key 

how could I get typeof ```Part``` value 'text'

I would appreciate your assistance.

Thank you!

**Comment by holtskinner** [comment]
Hi, this repository is focused on Generative AI using Google Cloud Vertex AI, not the Google AI Generative AI libraries. You can file an issue in this repository for assistance. https://github.com/google/generative-ai-js
