### ISSUE TITLE
candidate_count > 1 with InvalidArgument: 400 Only one candidate can be specified

### ISSUE THREAD

**Issue by lingjiekong** [GoogleCloudPlatform/generative-ai#406]
Given this code snippet from [here](https://ai.google.dev/tutorials/python_quickstart#generation_configuration)
```
model = genai.GenerativeModel('gemini-pro')
response = model.generate_content(
    'Tell me a story about a magic backpack.',
    generation_config=genai.types.GenerationConfig(
        # Only one candidate for now.
        candidate_count=1,
        stop_sequences=['x'],
        max_output_tokens=20,
        temperature=1.0)
)
```
It looks like candidate_count is configurable also based on [doc](https://ai.google.dev/models/gemini#model-attributes).

However, I got `InvalidArgument: 400 Only one candidate can be specified` after changing `candidate_count = 2`, so is more than 1 candidate not supported?

**Comment by holtskinner** [comment]
Hello, This repository is for [Generative AI with Vertex AI on Google Cloud](https://cloud.google.com/vertex-ai/docs/generative-ai/learn/overview), not the [Google AI Gemini/PaLM APIs](https://ai.google.dev/).

This looks like the Python client library, so you can try filing an issue in this repository:

https://github.com/google/generative-ai-python

or ask in the [Google Developers Community Discord #gemini-api channel](https://ai.google.dev/docs/discord).
