### ISSUE TITLE
[Bug]: Using Vertex AI Multimodal Embeddings and Vector Search lab ends on task 6 with error warning "you are not following instructions"

### ISSUE THREAD

**Issue by MichaelRajca** [GoogleCloudPlatform/generative-ai#438]
### File Name

Using Vertex AI Multimodal Embeddings and Vector Search - task 6

### What happened?

when you run the code from instructions it get stuck and throws an error ending the lab with warning that you are not following the instructions, I'm not entirely sure which code was it because the lab ended and I closed the window but somewhere around task 6, and it threatened to block my access so I'm not eager to check

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by holtskinner** [comment]
This can't be actioned in this repository. Seems to be a Qwiklabs issue. Re-open if issue re-occurs.
