### ISSUE TITLE
[Bug]: Unauthenticated: 401 Request is missing required authentication credential.

### ISSUE THREAD

**Issue by linhqyy** [GoogleCloudPlatform/generative-ai#454]
### File Name

gemini/use-cases/intro_multimodal_use_cases.ipynb

### What happened?

When running the Video input example part in the notebook intro_multimodal_use_cases.ipynb, I faced this error: 

-------Response--------
---------------------------------------------------------------------------
_MultiThreadedRendezvous                  Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/google/api_core/grpc_helpers.py](https://localhost:8080/#) in error_remapped_callable(*args, **kwargs)
    161             prefetch_first = getattr(callable_, "_prefetch_first_result_", True)
--> 162             return _StreamingResponseIterator(
    163                 result, prefetch_first_result=prefetch_first

7 frames
_MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAUTHENTICATED
	details = "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project."
	debug_error_string = "UNKNOWN:Error received from peer ipv4:64.233.182.95:443 {grpc_message:"Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.", grpc_status:16, created_time:"2024-03-21T10:43:28.414917135+00:00"}"
>

The above exception was the direct cause of the following exception:

Unauthenticated                           Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/google/api_core/grpc_helpers.py](https://localhost:8080/#) in error_remapped_callable(*args, **kwargs)
    164             )
    165         except grpc.RpcError as exc:
--> 166             raise exceptions.from_grpc_error(exc) from exc
    167 
    168     return error_remapped_callable

Unauthenticated: 401 Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.

------------------------------------------------------------------------------------------------------------------------------
The input image parts are working fine and only the video parts return error.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by haisonle001** [comment]
@linhqyy  How did you solve this bug?

**Comment by linhqyy** [comment]
> @linhqyy  How did you solve this bug?
> 
> 

I ran it on Colab Enterprise then problem solved 😅

**Comment by linhqyy** [comment]
@haisonle001 ohhh, thankss. We had difficulty during the Build with AI event in Hanoi last week and could only find the Colab Enterprise solution :))
