### ISSUE TITLE
[Bug]: Task 3 and Task 5 in gemini explorer certificate can't pass due to missing function

### ISSUE THREAD

**Issue by longchass** [GoogleCloudPlatform/generative-ai#529]
### File Name

generative-ai/gemini/function-calling/intro_function_calling.ipynb

### What happened?

Task 5 and Task 3 in cloud skill boost check can't be passed due to no according function available.

https://www.cloudskillsboost.google/course_templates/959/labs/461316

Need:
Weather function

Chat function for retail user

Happy to add the relevant code but I have no idea what the function name should be to pass the test.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by longchass** [comment]
Hi @koverholt, yes, it's working for me and Task 1,2,4 were working and were able to check off with the course content.

Thank you,
Long.

**Comment by koverholt** [comment]
Great, thanks for letting us know!
