### ISSUE TITLE
[Bug]: getting google.generativeai.types.generation_types.StopCandidateException

### ISSUE THREAD

**Issue by shubhamgajbhiye1994** [GoogleCloudPlatform/generative-ai#630]
### File Name

        chat = text_model.start_chat(history=[])         num_retries = 3         for retry in range(num_retries):             try:                 chat.send_message(json.dumps(txt_data) + "\n" + output_prompt)                 break             except google.api_core.exceptions.InternalServerError as e:                 if retry == num_retries - 1:                     raise e                 else:                     print(                         f"Internal Server Error. Retrying in 10 seconds... (Attempt {retry + 1}/{num_retries})"                     )                     time.sleep(10)          time.sleep(10)           if chat.history:             response = chat.history[-1].parts[0].text             extracted_data = response         else:             print("No response received from the model.")             extracted_data = {}         return extracted_data     except Exception as e:         print(traceback.print_exc())         print(f"Error processing txt input: {e}")         return {}

### What happened?

I am trying to build enitity extraction based on gemeni api  but sometime i am geeting below error , tried to fixed with chat histry cleanup but nothing is working out 

### Relevant log output

```shell
File "/teamspace/studios/this_studio/.lightning_studio/ocr_based_extraction.py", line 106, in extract_info_from_txt
    chat.send_message(json.dumps(txt_data) + "\n" + output_prompt)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/google/generativeai/generative_models.py", line 483, in send_message
    self._check_response(response=response, stream=stream)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/google/generativeai/generative_models.py", line 510, in _check_response
    raise generation_types.StopCandidateException(response.candidates[0])
google.generativeai.types.generation_types.StopCandidateException: index: 0
finish_reason: SAFETY
safety_ratings {
  category: HARM_CATEGORY_SEXUALLY_EXPLICIT
  probability: NEGLIGIBLE
}
safety_ratings {
  category: HARM_CATEGORY_HATE_SPEECH
  probability: LOW
}
safety_ratings {
  category: HARM_CATEGORY_HARASSMENT
  probability: MEDIUM
}
safety_ratings {
  category: HARM_CATEGORY_DANGEROUS_CONTENT
  probability: NEGLIGIBLE
}


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/teamspace/studios/this_studio/.lightning_studio/ocr_based_extraction.py", line 108, in extract_info_from_txt
    except google.api_core.exceptions.InternalServerError as e:
NameError: name 'google' is not defined
None
Error processing txt input: name 'google' is not defined
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by koverholt** [comment]
Thanks for the report! This repository is for [Generative AI with Vertex AI on Google Cloud](https://cloud.google.com/vertex-ai/docs/generative-ai/learn/overview), not the [Google AI Gemini/PaLM APIs](https://ai.google.dev/)

For issues with the Google AI Gemini API, refer to one of [these repositories](https://github.com/orgs/google/repositories?q=generative-ai) or the [Google Developers Community Discord #gemini-api channel](https://ai.google.dev/docs/discord).
