### ISSUE TITLE
[Bug]: Tuning Gemini with 500 rows takes endless hours and never stops

### ISSUE THREAD

**Issue by sidoncloud** [GoogleCloudPlatform/generative-ai#656]
### File Name

https://github.com/GoogleCloudPlatform/generative-ai/blob/main/gemini/tuning/gemini_supervised_tuning_qa.ipynb

### What happened?

Tuning Gemini with 500 rows takes and basic minimum hyperparam values takes 3+ hours if you cancel the job after 3 hours else it goes on and on forever and you'll see a hefty cloud bill - This is something all google cloud paying users need to be made aware of before they try out something that does not work. 

### Relevant log output

```shell
No output
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ali-Razmjoo** [comment]
I launched two different tunings, with a 660MB and 1100MB dataset, 18 hours ago. The first one is now 5% processed, and the second one is still validating the dataset. Now, the Gemini tuning is in preview, and it doesn't cost anything, but I am unsure if I would do it if it was billed. It's heartbreaking how long it takes.

**Comment by gericdong** [comment]
Thanks for reporting this issue. There have been changes with the Gemini tuning. Can you please try the new tuning examples here: https://github.com/GoogleCloudPlatform/generative-ai/tree/main/gemini/tuning? 
Closing this issue.

**Comment by sidoncloud** [comment]
No they dont work. Seems like closing the issues is the primary objective here rather than solving the underlying problem with all your SDKs. The new error says " **Converting from 'ChatCompletions' to 'GenerateContent' dataset format is currently not supported for this model.**" I am referring to the code in the below notebook.

[https://github.com/GoogleCloudPlatform/generative-ai/blob/main/gemini/tuning/supervised_finetuning_using_gemini.ipynb]
