### ISSUE TITLE
[Bug]: Error on Lab  04 Prompt Design in Vertex AI

### ISSUE THREAD

**Issue by elismasilva** [GoogleCloudPlatform/generative-ai#697]
### File Name

prompt/examples/*

### What happened?

Last progress verification is not working:
![image](https://github.com/GoogleCloudPlatform/generative-ai/assets/40075615/f7d50437-f71d-470c-a22b-2d41c37bd224)

inspecting networking is getting 302 error
![image](https://github.com/GoogleCloudPlatform/generative-ai/assets/40075615/0e153007-3490-4479-88ba-ebdc72115842)

On first lab (Prompt Design in Vertex AI): 
I already tried open and finishing all notebook on examples folders and not working , this step 7 is not found.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by elismasilva** [comment]
Other problem is Beginner: Introduction to Generative AI Learning Path

Prompt Design in Vertex AI (https://www.cloudskillsboost.google/paths/118/course_templates/976)

This Task 2 is not completing too,
![image](https://github.com/GoogleCloudPlatform/generative-ai/assets/40075615/5f60f9bc-cd83-4076-87a4-4ef2162ac65d)


Even doing ok its not working

**Comment by harvey56** [comment]
Hi @elismasilva 

Have you found a solution to this yet ? I am having the same issue, with the same training (Prompt design in Vertex AI)

In my case, it will validate the last step (_Improve response quality by including examples_), but it won't validate any of the 5 previous steps of **Task 2. Open generative-ai folder**

That tells me i don't have any cloud setting wrong or missing. Or it would not validate any of the 6 steps. I tried using Chrome, as I thought Google would have "unintentionally" made it difficult on Firefox, which is the browser I use. But it does not work with Chrome either.

The network requests all return a 2xx or 304, except for the shit load of requests to _https://www.recaptcha.net/recaptcha/api2/_ that are canceled.

**Comment by elismasilva** [comment]
> Hi @elismasilva
> 
> Have you found a solution to this yet ? I am having the same issue, with the same training (Prompt design in Vertex AI)
> 
> In my case, it will validate the last step (_Improve response quality by including examples_), but it won't validate any of the 5 previous steps of **Task 2. Open generative-ai folder**
> 
> That tells me i don't have any cloud setting wrong or missing. Or it would not validate any of the 6 steps. I tried using Chrome, as I thought Google would have "unintentionally" made it difficult on Firefox, which is the browser I use. But it does not work with Chrome either.
> 
> The network requests all return a 2xx or 304, except for the shit load of requests to _https://www.recaptcha.net/recaptcha/api2/_ that are canceled.

nop. i think its a backend problem.

**Comment by holtskinner** [comment]
Hi, these types of issues are not related to this GitHub repository. Please contact Qwiklabs/Cloud Skills Boost support `support@qwiklabs.com` with this issue.

**Comment by Moni123-k** [comment]
@holtskinner, I am facing the issue for all the with the Generative AI with Vertex AI: Text Prompt Design challenge lab. 

Check my progress is not working for all the tasks.

Can you help me
