### ISSUE TITLE
can't open Question Answering with Large Documents using LangChain notebook in Colab

### ISSUE THREAD

**Issue by markbpryan** [GoogleCloudPlatform/generative-ai#74]
when you try to run the Question Answering with Large Documents using LangChain https://github.com/GoogleCloudPlatform/generative-ai/blob/main/language/examples/document-qa/question_answering_large_documents_langchain.ipynb notebook in Colab by clicking on the **Run in Colab** link https://screenshot.googleplex.com/3z2uwdNUMpNKXCb from the example in github, you get **Notebook not found** message: https://screenshot.googleplex.com/5d7EzzPFWgL4yoa

If you click on the **Authorize with Github** link in that dialog and enter your github credentials you just get back to the  **Notebook not found** message again: https://screenshot.googleplex.com/5d7EzzPFWgL4yoa

FWIW, I have been able to run other notebooks in this repo in Colab (e.g. https://github.com/GoogleCloudPlatform/generative-ai/blob/main/language/examples/prompt-design/ideation.ipynb and https://github.com/GoogleCloudPlatform/generative-ai/blob/main/language/examples/prompt-design/text_classification.ipynb) with no issues.

**Comment by iamthuya** [comment]
Fixing all the links with this PR https://github.com/GoogleCloudPlatform/generative-ai/pull/101
