### ISSUE TITLE
[Bug]: PDF Document + Image analysis doesn't work as written 

### ISSUE THREAD

**Issue by darylducharme** [GoogleCloudPlatform/generative-ai#754]
### File Name

gemini/getting-started/intro_gemini_1_5_pro.ipynb

### What happened?

For the section that takes a PDF and an image and is supposed to tell you where the image is found in the PDF I get the following response back

> Please provide the PDF document and the image file so I can answer your question

I tried a couple different ways to pass both the PDF and image into the `model.generate_content()` call but I could not get it to give me a different response.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by G1tPlunge** [comment]
+1
