### ISSUE TITLE
Merge Retrieval taking long time to execute.

### ISSUE THREAD

**Issue by ravikumarmittal** [GoogleCloudPlatform/generative-ai#767]
### File Name

please find the code

### What happened?

**#invoke method is taking long time**

from langchain_openai import OpenAIEmbeddings
from langchain_community.vectorstores import PGVector
from langchain.chains.query_constructor.base import AttributeInfo
from langchain_openai import ChatOpenAI,OpenAI
from langchain.chains import RetrievalQA
from langchain_core.prompts.prompt import PromptTemplate
from langchain.retrievers import MergerRetriever
from langchain.retrievers import ContextualCompressionRetriever
from langchain.retrievers.document_compressors import EmbeddingsFilter
import datetime
import os

os.environ["OPENAI_API_KEY"]='your key'
connection = "postgresql+psycopg2://Administrator1:yourpassword@postgress-db-cr.postgres.database.azure.com:5432/testdb" 
collectiontest1 = "test1" 
collectiontest2 = "text2"
collectiontest3 = "text3" 

embeddings = OpenAIEmbeddings()
llm = ChatOpenAI(temperature=0)

metadata_field_info = [
    AttributeInfo(
        name="Data",
        description="Detail of the metadata",
        type="string",
    ),
    
]
document_content_description = "Brief summary "

vectorstore1 = PGVector(
    connection_string=connection, 
    embedding_function=embeddings, 
    collection_name=collectiontest1,    
    use_jsonb=True,
)

vectorstore2 = PGVector(
    embedding_function=embeddings,    
    collection_name=collectiontest2,
    connection_string=connection,    
        use_jsonb=True,
)
vectorstore3 = PGVector(
    embedding_function=embeddings,    
    collection_name=collectiontest3,
    connection_string=connection,    
        use_jsonb=True,
)

template = """Use only context to answer the question. 
Use ten sentences maximum. 

{context}
Question: {question}
Helpful Answer:"""

QA_CHAIN_PROMPT = PromptTemplate(input_variables=["context", "question"], template=template)

embeddings_filter = EmbeddingsFilter(embeddings=embeddings, similarity_threshold=0.76)
retrieverHardware = ContextualCompressionRetriever(
                base_compressor=embeddings_filter, base_retriever=vectorstore1.as_retriever(search_type="similarity", search_kwargs={"k": 5, "include_metadata": True})
            )
retrieverSoftware = ContextualCompressionRetriever(
                base_compressor=embeddings_filter, base_retriever=vectorstore2.as_retriever(search_type="similarity", search_kwargs={"k": 5, "include_metadata": True})
            )

retrieverConfig = ContextualCompressionRetriever(
                base_compressor=embeddings_filter, base_retriever=vectorstore3.as_retriever(search_type="similarity", search_kwargs={"k": 5, "include_metadata": True})
            )

lotr = MergerRetriever(retrievers=[retrieverHardware,retrieverSoftware,retrieverConfig])
llm = ChatOpenAI(model_name="gpt-3.5-turbo", temperature=0,max_tokens=1000,timeout=None,max_retries=2,streaming=True)
qa = RetrievalQA.from_chain_type(llm,
                                chain_type='stuff',
                                retriever=lotr,
                                #return_source_documents=True,     
                                chain_type_kwargs={"prompt": QA_CHAIN_PROMPT},
                                verbose=True                                
                                )

query = "provide me count of asset having ram >2gb"
print( datetime.datetime.now())
**data=qa.invoke(query) 
print(data)   
print( datetime.datetime.now())**

### Relevant log output

```shell
it is taking long time about 1 minute to execute the invoke method
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by holtskinner** [comment]
This issue doesn't seem to be related to this repository. Please repost in the https://github.com/langchain-ai/langchain repository.
