### ISSUE TITLE
[Bug]: intro_function_calling.ipynb - prompt for stock in Mountain View never calls get_store_location function

### ISSUE THREAD

**Issue by ankurkotwal** [GoogleCloudPlatform/generative-ai#792]
### File Name

gemini/function-calling/intro_function_calling.ipynb

### What happened?

About 40% into the lab, there is a prompt that asks for the Pixel 8 stock levels in Mountain View as follows:
> prompt = """
> What about the Pixel 8? Is there a store in
> Mountain View, CA that I can visit to try one out?
> """
> 
> response = chat.send_message(prompt)
> response.candidates[0].content.parts[0]`

The expected response in the notebook is as follows:
>Again, you get a response with structured data. This time, the Gemini model selected the get_store_location function.

I've run this prompt many times and I always get the following output
> function_call {
>   name: "get_product_info"
>   args {
>     fields {
>       key: "product_name"
>       value {
>         string_value: "Pixel 8"
>       }
>     }
>   }
> }

Since the following step provides a mock api response, it's able to continue but the above response is incorrect.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by koverholt** [comment]
Thanks for catching this and reporting! This is likely happening because of changes in the behavior of Gemini Function Calling from Gemini 1.0 Pro to Gemini 1.5 Pro. I'll open a PR to fix the function calling order and add more explanatory text regarding the expected behavior.
