### ISSUE TITLE
[Bug]: Check my progress not working In task 1: [Multimodal Retrieval Augmented Generation (RAG) using the Vertex AI Gemini API - Install Vertex AI SDK for Python and import libraries.]

### ISSUE THREAD

**Issue by Namasivaayam-L** [GoogleCloudPlatform/generative-ai#796]
### File Name

intro_multimodal_rag.ipynb

### What happened?

What happened?
Check my Progress is not working for task 1: Install Vertex AI SDK for Python and import libraries.
I think there's a bug in the activity tracker. Please rectify this. Other prompts progress is detected and taken into account correctly. Thanks.
![image](https://github.com/GoogleCloudPlatform/generative-ai/assets/83755082/1fb4cb18-2f6e-47c9-8328-7915aac29871)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Namasivaayam-L** [comment]
Hey guys, any possible fixes for this?

**Comment by holtskinner** [comment]
Hi, these types of issues are not related to this GitHub repository. Please contact Qwiklabs/Cloud Skills Boost support `support@qwiklabs.com` with this issue.
