### ISSUE TITLE
[Bug]: Check my progress not working : [Build LangChain Applications using Vertex AI - Create Text Embeddings for a Vector Store using LangChain]

### ISSUE THREAD

**Issue by Namasivaayam-L** [GoogleCloudPlatform/generative-ai#797]
### File Name

create_text_embeddings_using_langchain.ipynb

### What happened?

Check my Progress is not working for task 1: **Install Vertex AI SDK for Python and import libraries.**
I think there's a bug in the activity tracker, please verify for all courses for this bug, because I'm facing this issue for the third time. Please rectify this. Thanks.

![image](https://github.com/GoogleCloudPlatform/generative-ai/assets/83755082/d99c0985-d06e-4957-9d72-6555503c8d7e)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Namasivaayam-L** [comment]
Hey guys, any possible fixes for this?

**Comment by holtskinner** [comment]
Hi, these types of issues are not related to this GitHub repository. Please contact Qwiklabs/Cloud Skills Boost support `support@qwiklabs.com` with this issue.

**Comment by StavrosD** [comment]
I had the same problem until I realized that I had to replace the PROJECT_ID and LOCATION as noted in the project instructions.

Did you set the PROJECT_ID and LOCATION ?

**Comment by Namasivaayam-L** [comment]
Yeah, that wasn't the issue.
