### ISSUE TITLE
[Bug]: AttributeError: 'Part' object has no attribute 'whichOneof'

### ISSUE THREAD

**Issue by jamietdavidson** [GoogleCloudPlatform/generative-ai#876]
### File Name

https://github.com/google-gemini/cookbook/blob/main/quickstarts/Function_calling.ipynb

### What happened?

Following the cookbook above, the following error is found text. Note that it still works, it's just misleading that the text is showing error contents when calling a function.

```
Traceback (most recent call last):   
  File "<string>", line 1, in <module>   
  File ".../env/lib/python3.10/site-packages/google/generativeai/types/generation_types.py", line 465, in text
    part_type = protos.Part.pb(part).whichOneof("data") 
AttributeError: 'Part' object has no attribute 'whichOneof'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by holtskinner** [comment]
The notebook you're referring to is not part of this repository. Please file an issue in the `google-gemini/cookbook` repository.

https://github.com/google-gemini/cookbook/issues/new?assignees=&labels=type%3Abug&projects=&template=bug_report.yml
