### ISSUE TITLE
Incorrect notes: "This is more efficient than Map-Reduce but less efficient."

### ISSUE THREAD

**Issue by sathishvj** [GoogleCloudPlatform/generative-ai#90]
In "question_answering_large_documents_langchain.ipynb", notes say: This is more efficient than Map-Reduce but less efficient.

This needs to be rewritten.

**Comment by holtskinner** [comment]
This text was rewritten in https://github.com/GoogleCloudPlatform/generative-ai/blob/main/language/use-cases/document-qa/question_answering_documents_langchain.ipynb to say:

> This is more accurate than Map-Reduce but less efficient.
