### ISSUE TITLE
google-cloud-aiplatform version errors

### ISSUE THREAD

**Issue by yogeshhk** [GoogleCloudPlatform/generative-ai#91]
google-cloud-aiplatform==1.26 is needed to run langchain.llms.VertexAI but it gives error in chat.send_message as 
is_blocked=safety_attributes.get("blocked", False),
AttributeError: 'list' object has no attribute 'get'

https://github.com/googleapis/python-aiplatform/issues/2337 suggests soution to be downgrade to google-cloud-aiplatform==1.25 but then the LangChain does not work

Need version that resolves both.

**Comment by sasha-gitg** [comment]
Release 1.27 should resolve this issue.

**Comment by yogeshhk** [comment]
Confirmed that 1.27 resolves both the issues. Thanks for letting me know @sasha-gitg

**Comment by Ark-kun** [comment]
For clarity: Only version `1.26.1` is affected. Both `1.26.0` and `1.27.0` are working.
